FROM ghcr.io/anonymousx97/docker:main

COPY start setup

RUN \
    apt-get update -y && apt-get install -y busybox && \
    chmod +x setup && \
    ./setup --setup-repo --install-reqs --run-extra-boot-scripts

CMD ./setup --run