#!bin/sh

echo "${GH_TOKEN}" > ~/.git-credentials
git config --global credential.helper store

if [ -d "ubot" ]; then
    rm -rf ubot
fi


git clone -q --depth=1 "${UPSTREAM_REPO:-"https://github.com/anonymous-x97/UX-jutsu"}" ubot
cd ubot
pip -q install --no-cache-dir -r req*.txt
bash run
